### ISSUE TITLE
SDK still uses old kernel.inc with --kernel-source

### ISSUE THREAD

**Issue by Willem3141** [KnightOS/KnightOS#249]
When using, in a userspace program, the `--kernel-source=...` option to use a custom kernel, it seems like the assembler still uses the kernel header from the "normal" kernel. This causes problems when the jump table of the local kernel is modified, since all of the pcalls will point to the wrong location.

Running `make clean` and then `make` on either the kernel source or the userspace program doesn't fix the issue.

I think the problem is caused by the fact that the SDK downloads the kernel headers instead of taking them from the indicated kernel source directory:

```
$ knightos init --kernel-source=~/Documenten/Persoonlijk/KnightOS/kernel/
Notice: Rebuilding existing environment
Found existing project: calendar
[...]
Downloading core/kernel-headers  100%
[...]
Installing core/kernel-headers...
[...]
```

After this, `.knightos/include/kernel.inc` contains the old header indeed.

(Originally reported [here](http://lists.knightos.org/pipermail/knightos/2015-January/000017.html).)

**Comment by SirCmpwn** [comment]
This is fixed as of https://github.com/KnightOS/sdk/commit/c3fdf7f9de6f84dc9afdb7dbb6c05033d5d4d1d2.

**Comment by Willem3141** [comment]
I have upgraded the SDK, but I'm still having the same issue.

To reproduce, do the following:

* clone the kernel, and make one change: in `src/01/jumptable.config` swap `drawStr` and `drawDecA`
* start a new project using that kernel (`knightos init hello --kernel-source=/path/to/the/kernel/clone`)
* invoke `make run`

Then you get the number 0 instead of the text "Hello, world" on the emulator screen, which demonstrates that `drawDecA` is called instead of `drawStr`.

**Comment by Willem3141** [comment]
A workaround for now is manually copying `<kernel-directory>/bin/include/kernel.inc` to `<app-directory>/.knightos/include/kernel.inc`.

**Comment by neersighted** [comment]
Bump?

**Comment by SirCmpwn** [comment]
No news.

**Comment by Willem3141** [comment]
Wasn't this fixed already? At least, I've got it working here :confused:

**Comment by SirCmpwn** [comment]
I thought it was fixed, too, but I haven't verified it since the issue was re-opened.

**Comment by SirCmpwn** [comment]
Figured out what the issue is here - it's re-extracting the kernel-headers package on top of the local kernel's headers. I'll see about a fix today.

**Comment by SirCmpwn** [comment]
Requires re-initing your workspace (`knightos init`) to get the fix.
